FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/gestion-exellence/firestore/indexes?create_composite=Cl1wcm9qZWN0cy9nZXN0aW9uLWV4ZWxsZW5jZS9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza01hbmFnZW1lbnRUYXNrcy9pbmRleGVzL18QARoNCgl1cGRhdGVkQXQQAhoRCg1jdXJyZW50U3RhdHVzEAIaDAoIX19uYW1lX18QAg . The query contains range and inequality filters on multiple fields, please refer to the documentation for index selection best practices: https://cloud.google.com/firestore/docs/query-data/multiple-range-fields.